### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by rka** [Depado/goploader#40]
If its not a huge work maybe there could be a language file so we can have all the visible parts there then its easy to manage in the future.

**Comment by Depado** [comment]
That wouldn't be too hard I think, except if you want the documentation translated too.

**Comment by rka** [comment]
Noo noo just the basic stuff like the buttons. Basically the stuff a user can see in "sensitive_mode: true"

**Comment by Depado** [comment]
Something like :
```yaml
translation:
    upload_button: "Upload"
    type_selector: 
        - "File"
        - "Text"
    file_chooser: "Choose a file..."
    text_placeholder: "Paste your text here..."
    restriction:
        - "No Restriction"
        - "One Download"
```

The only problem there is the lifetime selector. As this will be dynamically generated, I don't know how I could provide a translation system. I'll try to think of something, tell me if my proposal for the configuration file looks good to you :)
